### ISSUE TITLE
Priority: 10 - MYC currently formats links (http://...) as text not as live links. 

### ISSUE THREAD

**Issue by mentionthewar** [nationalarchives/manage-your-collections#4]
Users have specifically requested this functionality to improve linking with 3rd party services (e.g. to photos on Flickr)

**Comment by mcieslak** [comment]
Priority score: 6 (prioritised with Jo 22/03/19)

Benefit to user - 3
Benefit to TNA - 1
Impact of doing nothing - 2

System to recognise a href tags so users can link within data

**Comment by Puththiran** [comment]
Cross site reference is always carry some risk, I've asked @ma2ts & @ggrannum about the details. @ggrannum said he will confirm with the cataloging team about it.

**Comment by julieguthrie** [comment]
NEW PRIORITY SCORE AGREED: 
benefit to user: 3
benefit to TNA: 4
impact of doing nothing: 3
TOTAL 10

Expect this to be a small number of fields (2-3), Jo/Caroline to confirm, to enable estimating.

@Puththiran thinks this is a Medium effort task & would be Discovery wide.

**Comment by mentionthewar** [comment]
On consideration we would want links to operate in three fields: Description (Scope and Content), Finding Aids and Notes. They would not operate in any other field.

We currently publish external links on pages such as https://discovery.nationalarchives.gov.uk/details/r/N14663825 but these use are obviously a bit different from the usual catalogue pages.

**Comment by julieguthrie** [comment]
@netdesignr you said one sprint, how much actual time would this take? Is there someone you can handover to?

**Comment by mentionthewar** [comment]
This is an example of the sort of thing that might come in:
https://discovery.nationalarchives.gov.uk/details/r/7db80b53-9202-441f-9635-3c14131293a6
(with some links in the middle of it)

Here are two examples of external links being handled at the moment. In an authority file:
https://discovery.nationalarchives.gov.uk/details/c/F257148

and in an index entry:
https://discovery.nationalarchives.gov.uk/details/r/N13783964

**Comment by ggrannum** [comment]
Is there a reason why other fields cannot contain links?

**Comment by Puththiran** [comment]
[17-06-2020 Maria]
IN PROGRESS
Front end patterns for this have recently been created by Matt Blair & signed off by Jo Pugh - Back end work needs to be estimated by Gnanesh

**Comment by Puththiran** [comment]
#4 allow live links on Description (Scope and Content), Finding Aids and Notes.

Currently if you add the extref to Description it will show as live link on the discovery details page.
Eg: https://discovery.nationalarchives.gov.uk/details/r/C4177
We can extend the same feature on Discovery to “Finding Aids” and “Notes” as requested and users have to update link as extref as shown below
<extref href='http://www.middlesbrough.gov.uk/teessidearchives'>http://www.middlesbrough.gov.uk/teessidearchives</extref>

I’ve following questions
Is this is the acceptable implementation for ASD and the team?
Since we are making changes to the Discovery display rule across all records, I hope we are not breaking any rules?
Although EAD 2002 recommend ‘extref’ in Finding Aids, I hope having in other fields is not much of violation?
https://www.loc.gov/ead/tglib/elements/otherfindaid.html

**Comment by ma2ts** [comment]
Here's an example MYC record containing both fields: "Unpublished Finding Aids" and "Note" - the latter also contains hyperlinks to external websites: https://discovery.nationalarchives.gov.uk/details/r/086f04b7-67fe-4c10-a640-0cf03cf69949

**Comment by mentionthewar** [comment]
Live links now available. Sensational.
